'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('car', [
      {
        registration_number: 'ABC1234',
        brand: 'Toyota',
        vin: 'JT2BF22K3W0123456',
        model: 'Corolla',
        production_date: '2020-05-15',
        fuel_level: 20.00,
        mileage: 45000,
        status: 'In use',
        geo_latitude: 53.9001,
        geo_longitude: 27.5667,
        createdAt: new Date(),
        updatedAt: new Date(),
        fk_run_id: 1,
      },
      {
        registration_number: 'XYZ9876',
        brand: 'Honda',
        vin: 'JHMCB7650LC012345',
        model: 'Civic',
        production_date: '2019-03-10',
        fuel_level: 50.00,
        mileage: 35000,
        status: 'Free',
        geo_latitude: 53.9075,
        geo_longitude: 27.5625,
        createdAt: new Date(),
        updatedAt: new Date(),
        fk_run_id: 2,
      },
      {
        registration_number: 'POPULAR1',
        brand: 'Volkswagen',
        vin: 'WVWZZZ1JZ3W123456',
        model: 'Golf',
        production_date: '2018-07-15',
        fuel_level: 20.00,
        mileage: 120000,
        status: 'Free',
        geo_latitude: 53.9,
        geo_longitude: 27.56,
        createdAt: new Date(),
        updatedAt: new Date(),
        fk_run_id: 3,
      },
      {
        registration_number: 'CBC1235',
        brand: 'Toyota',
        vin: 'JT4RN01P1K7020837',
        model: 'Corolla',
        production_date: '2020-05-15',
        fuel_level: 75.00, 
        mileage: 150000,
        status: 'Reserved',
        geo_latitude: 40.7128,
        geo_longitude: -74.0060,
        fk_run_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        registration_number: 'XYZ789',
        brand: 'Honda',
        vin: '2HGFC2F50KH702083',
        model: 'Civic',
        production_date: '2019-11-22',
        fuel_level: 10.00,
        mileage: 18700,
        status: 'Reserved',
        geo_latitude: 34.0522,
        geo_longitude: -118.2437,
        fk_run_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        registration_number: 'TRTE89',
        brand: 'BMW',
        vin: '3CFRC2F50KH702124',
        model: 'X5',
        production_date: '2018-02-20',
        fuel_level: 10.00,
        mileage: 18700,
        status: 'In use',
        geo_latitude: 34.0522,
        geo_longitude: -118.2437,
        fk_run_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        registration_number: 'GHI789',
        brand: 'Tesla',
        vin: '5YJ3E1EB0KF123456',
        model: 'Model 3',
        production_date: '2022-01-05',
        fuel_level: 65.00, 
        mileage: 3200,
        status: 'Reserved',
        geo_latitude: 37.7749,
        geo_longitude: -122.4194,
        fk_run_id: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
  },
};
